resolver: lts-21.15

ghc-options:
  $everything: -split-sections -haddock
  $locals: -fwrite-ide-info -hiedir=.hie -fmax-relevant-binds=0

packages:
  - aura/
  - aur/
  - aursec/

extra-deps:
  - versions-6.0.3
