resolver: lts-12.0

packages:
  - aura/
  - aur/
  - arel/

extra-deps:
  - algebraic-graphs-0.1.1.1
  - compactable-0.1.2.2
  - git: https://github.com/knrafto/language-bash
    commit: 2c4839b81daa11cae06f3ee6f65c838ff71681c8
  - git: https://github.com/andrewthad/non-empty-containers
    commit: a8293c40382983622cea9703da7dc841093e016c
