resolver: lts-16.7

ghc-options:
  $everything: -split-sections
  $locals: -fwrite-ide-info -hiedir=.hie -fmax-relevant-binds=0

nix:
  shell-file: nix/stack.nix

packages:
  - aura/
  - aur/
  - aursec/

extra-deps:
  - aeson-1.5.0.0  # Pinned to avoid `these` dependency.
