resolver: lts-17.10

ghc-options:
  $everything: -split-sections -haddock
  $locals: -fwrite-ide-info -hiedir=.hie -fmax-relevant-binds=0

nix:
  shell-file: nix/stack.nix

packages:
  - aura/
  - aur/
  - aursec/
