resolver: lts-15.5

ghc-options: {"$locals": -fwrite-ide-info}

flags:
  these:
    aeson: false
    assoc: false
    semigroupoids: false
    QuickCheck: false

packages:
  - aura/
  - aur/
  - aur-security/

extra-deps:
  - language-bash-0.9.0
  - paths-0.2.0.0
  - witherable-class-0
