resolver: lts-16.19

ghc-options:
  $everything: -split-sections -haddock
  $locals: -fwrite-ide-info -hiedir=.hie -fmax-relevant-binds=0

nix:
  shell-file: nix/stack.nix

packages:
  - aura/
  - aur/
  - aursec/

extra-deps:
  - versions-4.0.0
