resolver: lts-12.2

packages:
  - aura/
  - aur/
  - arel/

extra-deps:
  - algebraic-graphs-0.1.1.1
  - compactable-0.1.2.2
  # - language-bash-0.7.1
  - git: https://github.com/knrafto/language-bash
    commit: a4d6262e49db62614744968939594df8c5bd6ae4
  - git: https://github.com/andrewthad/non-empty-containers
    commit: a8293c40382983622cea9703da7dc841093e016c
