resolver: lts-13.20

packages:
  - aura/
  - aur/
  - arel/
  - aur-security/

extra-deps:
  - compactable-0.1.2.3
  - fused-effects-0.4.0.0
  - language-bash-0.8.0
  - non-empty-containers-0.1.4.0
  - paths-0.2.0.0
  - throttled-1.1.0
