resolver: lts-18.5

ghc-options:
  $everything: -split-sections -haddock
  $locals: -fwrite-ide-info -hiedir=.hie -fmax-relevant-binds=0

nix:
  shell-file: nix/stack.nix

flags:
  these:
    assoc: false
  strict:
    assoc: false

packages:
  - aura/
  - aur/
  - aursec/
