resolver: lts-13.22

packages:
  - aura/
  - aur/
  - arel/
  - aur-security/

extra-deps:
  - compactable-0.1.2.3
  - fused-effects-0.4.0.0
  - language-bash-0.8.0
  - nonempty-containers-0.2.0.0
  - paths-0.2.0.0
  - scheduler-1.1.0
  - servant-0.16.0.1
  - servant-client-0.16
  - servant-client-core-0.16
