resolver: lts-16.5

ghc-options: {"$locals": -fwrite-ide-info -hiedir=.hie -fmax-relevant-binds=0}

packages:
  - aura/
  - aur/
  - aursec/

extra-deps:
  - aeson-1.5.0.0  # Pinned to avoid `these` dependency.
