resolver: lts-13.21

packages:
  - aura/
  - aur/
  - arel/
  - aur-security/

extra-deps:
  - compactable-0.1.2.3
  - language-bash-0.8.0
  - nonempty-containers-0.2.0.0
  - paths-0.2.0.0
  - scheduler-1.1.0
