resolver: lts-15.0

ghc-options: {"$locals": -ddump-to-file -ddump-hi}

flags:
  these:
    aeson: false
    assoc: false
    semigroupoids: false
    QuickCheck: false

packages:
  - aura/
  - aur/
  - aur-security/

extra-deps:
  - language-bash-0.8.0
  - paths-0.2.0.0
