resolver: lts-18.19

ghc-options:
  $everything: -split-sections -haddock
  $locals: -fwrite-ide-info -hiedir=.hie -fmax-relevant-binds=0

nix:
  shell-file: nix/stack.nix

flags:
  these:
    assoc: false
  strict:
    assoc: false

packages:
  - aura/
  - aur/
  - aursec/

extra-deps:
  - OneTuple-0.3.1
  - aeson-2.0.2.0
  - algebraic-graphs-0.6
  - hashable-1.4.0.1
  - semialign-1.2.0.1
  - text-short-0.1.4
  - time-compat-1.9.6.1
