[package]
name = "aura-core"
version = "0.1.0"
authors = ["Colin Woodbury <colin@fosskers.ca>"]
edition = "2021"

[dependencies]
alpm = "2.2"
alpm-utils = "1.1"
aura-arch = { path = "../aura-arch" }
chrono = { version = "0.4", features = ["serde"] }
itertools = "0.10"
log = "0.4"
nonempty = "0.7"
petgraph = { version = "0.6", default-features = false }
r2d2 = "0.8"
rayon = "1.5"
raur-curl = { path = "../raur-curl" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
srcinfo = "1.0"
validated = { version = "0.1", features = ["rayon"] }
