[package]
name = "aura-core"
version = "0.1.0"
authors = ["Colin Woodbury <colin@fosskers.ca>"]
edition = "2021"

[dependencies]
alpm = "2.0"
aura-arch = { path = "../aura-arch" }
chrono = { version = "0.4", features = ["serde"] }
itertools = "0.10"
petgraph = { version = "0.6", default-features = false }
rayon = "1.5"
raur-curl = { path = "../raur-curl" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
