[package]
name = "aura"
version = "4.0.0-rc1"
authors = ["Colin Woodbury <colin@fosskers.ca>"]
edition = "2018"

[dependencies]
alpm = "1.1"
aura-arch = { path = "../aura-arch" }
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
rustyline = "6.3"
simplelog = "0.8"
termcolor = "1.1"
ubyte = "0.10"
