name:        aur-security
version:     '1.0.0'
synopsis:    Sweeps the AUR for security flaws in PKGBUILDs.
description: Sweeps the AUR for security flaws in PKGBUILDs.
category:    System
author:      Colin Woodbury
maintainer:  colin@fosskers.ca
homepage:    https://github.com/aurapm/aura
license:     GPL-3

ghc-options:
  - -Wall
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Widentities

default-extensions:
  - NoImplicitPrelude

executables:
  aur-security:
    source-dirs: .
    main: Main.hs
    dependencies:
      - base >= 4.8 && < 4.13
      - base-prelude >= 1.2 && < 1.4
      - aura
      - async
      - compactable >= 0.1 && < 0.2
      - errors >= 2.3 && < 2.4
      - http-client >= 0.5 && < 0.6
      - http-client-tls >= 0.3 && < 0.4
      - language-bash >= 0.8 && < 0.9
      - pretty-simple >= 2.1 && < 2.3
      - split >= 0.2 && < 0.3
      - text
    ghc-options:
      - -threaded
      - -O2
      - -with-rtsopts=-N
