[workspace]
members = ["aura", "aura-core", "aura-arch", "aura-common", "raur-curl"]

[patch.crates-io]
raur = { git = "https://gitlab.com/davidbittner/raur/", rev = "9cf07a03489a34f47192992105b55ba9140d9fb7" }

[profile.release]
lto = true
panic = "abort"
# opt-level = "z"  # Reduces final stripped size by ~20%.
