[workspace]
members = [
# The executable
"aura-pm",
# Core libraries
"aura-core",
# Ecosystem libraries
"r2d2-alpm",
]
resolver = "2"

[profile.release]
lto = true
panic = "abort"
strip = true
opt-level = "z"  # Reduces final stripped size by ~20%.
codegen-units = 1
