[workspace]
members = [
# The executable
"aura",
# Core libraries
"aura-core", "aura-arch", "aura-common",
# Ecosystem libraries
"raur-curl", "r2d2-alpm"
]

[profile.release]
lto = true
panic = "abort"
strip = true
opt-level = "z"  # Reduces final stripped size by ~20%.
