name:        arel
version:     '1.1.0'
synopsis:    Create an Aura release.
description: Create an Aura release.
category:    System
author:      Colin Woodbury
maintainer:  colin@fosskers.ca
license:     GPL-3

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -fwarn-name-shadowing
  - -fwarn-unused-matches
  - -fwarn-incomplete-patterns
  - -fwarn-incomplete-uni-patterns

dependencies:
  - base >= 4.8 && < 4.12
  - optparse-generic >= 1.1 && < 1.4
  - shelly >= 1.6 && < 1.9
  - text >= 1.2 && < 1.3

executables:
  arel:
    source-dirs: .
    main: arel.hs
    other-modules: []
