name:                aur
version:             6.0.0.2
synopsis:            Access metadata from the Arch Linux User Repository.
description:         Access package information from Arch Linux\'s AUR via its
                     RPC interface. The main exposed functions reflect those of the RPC.

                     `info` gets metadata for one package.
                     `search` gets limited metadata for packages that match a given regex.

                     By default this library supports version 5 of the RPC,
                     and hence version 4.2+ of the AUR.

homepage:            https://github.com/aurapm/aura
license:             GPL-3
author:              Colin Woodbury
maintainer:          colin@fosskers.ca
copyright:           2018 Colin Woodbury
category:            Linux

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -fwarn-name-shadowing
  - -fwarn-unused-matches
  - -fwarn-incomplete-patterns
  - -fwarn-redundant-constraints
  - -Wincomplete-uni-patterns

dependencies:
  - base >= 4.10 && < 4.12
  - http-client >= 0.5 && < 0.6

library:
  source-dirs: .
  other-modules: []
  dependencies:
    - aeson >= 0.9 && < 1.4
    - servant >= 0.9 && < 0.14
    - servant-client >= 0.13 && < 0.14
    - text

tests:
  aur-test:
    main: Test.hs
    source-dirs: tests
    other-modules: []
    ghc-options:
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - aur
      - tasty >= 0.11 && < 2.0
      - tasty-hunit >= 0.9 && < 0.11
      - http-client-tls >= 0.3 && < 0.4
