name: Haskell
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup GHC
        uses: haskell/actions/setup@v2
        with:
          ghc-version: "9.4.8"
          enable-stack: true
          stack-version: "latest"

      - name: Clone project
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('haskell/stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Build and run tests
        run: |
          cd haskell/
          stack test --fast --no-terminal --system-ghc
