name: Rust

on:
  push:
    branches: [master]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: Install Rust
        run: pacman -Sy rust gcc glibc openssl pkgconf --noconfirm

      - name: Clone Project
        uses: actions/checkout@v3

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          working-directory: rust/

      - name: Build and Test
        run: |
          cd rust/
          cargo test
